### ISSUE TITLE
Date in display is inaccurate

### ISSUE THREAD

**Issue by thc1967** [charliekassel/vuejs-datepicker#200]
Control:

```php
                        <date-picker wrapper-class="has-icons-right"
                            input-class="input is-fullwidth{{ $errors->has('solution_date') ? ' is-danger' : '' }}"
                            name="solution_date"
                            format="yyyy-MM-dd"
                            v-model="solutionDate.date"></date-picker>
```

Vue:

```javascript
        solutionDate: {
            date: '2017-06-26'
        }
```

Result in the UI: ```2017-06-25```

What's going wrong?

**Comment by minesh93** [comment]
When I looked at the date in vue devtools it was showing the date as have the time as 23:00:00 for the date BEFORE, I'm working on a fix for it so far it seems to be working when no date is applied but once a date is preloaded on render it seems to mess up there. 😞 https://github.com/minesh93/vuejs-datepicker my attempt to fix it in progress

**Comment by egomolka** [comment]
Having the same issue here. I stepped through the code and found that the problem was that the JavaScript runtime is treating input dates as UTC timestamps with the time set to midnight (all zeroes) rather than dates. In the init function in Datepicker.vue, the date comes in correctly from the database. As the value is passed on to the setValue function, it is immediately converted to a localized timestamp, which changes the date for anyone west of the UTC timezone. For example, it handles a date of July 1, 2017 as midnight UTC time on July 1, 2017. It then adjusts for local time and displays a date of Jun 30, 2017 for my time zone.

**Comment by charliekassel** [comment]
FYI, I'm looking at preserving the time instead of zeroing it out which should solve a lot of these timezone issues.

**Comment by egomolka** [comment]
That would be awesome. Thx!

**Comment by charliekassel** [comment]
This change has been merged in v0.9.0 please confirm if it resolves your issue.

**Comment by FSevaistre** [comment]
Nope, I still have the issue :'(
selectedDate is set at "1980-06-24T22:00:00.000Z" when I select 25 July 1980

**Comment by charliekassel** [comment]
That doesn't look like you are using the latest realease. Can you corfirm the version?

**Comment by FSevaistre** [comment]
My bad it seems to be ok now
Thanks for this awesome component !

**Comment by mikeyudin** [comment]
I'm still having this issue (day minus 1) unless I pass in a time to the datepicker (IE "1980-06-24 00:00:00" displays 1980-06-24, but "1980-06-24" displays "1980-06-23")

**Comment by egomolka** [comment]
I have upgraded my version of vuejs-datepicker, and I am still seeing the issue. Additionally, if I set a date programmatically, it now gets stored on the database as one day later. Luckily, in my current application, I only care about the date and month. That allows me to use a workaround for this bug; I simply set the date to the second day of the month, regardless of user input. I then only display the year and month.

**Comment by codymoorhouse** [comment]
I believe this is a result of the timezone interfering with the date object in strange ways. In my particular instance all my times are off by 6 hrs, which happens to be my timezone. Therefore, when I change my time it can cause the date to go forwards or if I set my time past 18:00 hrs.

**Comment by KoiLVeD** [comment]
@charliekassel  i use v0.9.0 and have this problem(( help pls

**Comment by charliekassel** [comment]
One of the issues - perhaps for @mikeyudin - is that if you pass a string as a value to the datepicker in the format `YYYY-MM-DD` it constructs the date object in UTC

**Comment by mikeyudin** [comment]
@charliekassel Yes, it constructs "YYYY-MM-DD" and then displays in the user's local timezone (in my case, -0500).  I do store the timezone that the date was saved in, but it's in a separate property, and I have no way of datepicker.  So, I'm forced to create a computed getter/setter to construct a proper date object -- and then set the property on my object -- instead of referencing the property on my object directly.  

A bit inconvenient.  Perhaps I should create a PR to accept a timezone prop (or some other solution)?  If that's the case, what standard would we use?  I'm open to suggestions and willing to code the required change.

**Comment by minesh93** [comment]
I've got my PR active if you want a quick fix, all that does it negate the time zone. 
I haven't tried passing in a time however!

**Comment by charliekassel** [comment]
@mikeyudin this is most likely due to javascript `Date.parse` functionality when `new Date` is constructed with a string without time it construct in UTC.

> Support for ISO 8601 formats differs in that date-only strings (e.g. "1970-01-01") are treated as UTC, not local.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by DavidStrada** [comment]
@charliekassel Hi first off thanks for the lib :).

I'm experiencing the same problem as describe above. I pass the value as string e.g. `format="yyyy-MM-dd" value="2017-08-10"` on input `2017-08-09` it's always 1 day behind.

**Comment by Zaskoda** [comment]
I am experiencing this as well. version 0.9.16

**Comment by walkerdigital** [comment]
+1

**Comment by charliekassel** [comment]
As per my comment above - when you construct a Date object with a YYYY-MM-DD string it will create it in UTC not local time.
These are the quirks of javascript's Date object and not this library.
