### ISSUE TITLE
Unknown custom element: <my-component> - did you register the component correctly? For recursive components, make sure to provide the "name" option.  found in

### ISSUE THREAD

**Issue by rashed-jitu** [charliekassel/vuejs-datepicker#360]
I am getting this issue: 
![image](https://user-images.githubusercontent.com/17926071/33253688-e77a908c-d36e-11e7-8246-591cfecdd2a1.png)

I am using webpack-simple. And I have imported it in this way as a global component: 
![image](https://user-images.githubusercontent.com/17926071/33253702-0333f6ec-d36f-11e7-95f6-d620be87ca54.png)

And used the component tag in this way:
![image](https://user-images.githubusercontent.com/17926071/33253809-962d74c8-d36f-11e7-80f1-cd835e258339.png)

**Comment by liam-potter** [comment]
`<my-component>` is just an example component from the documentation. Instead you should add `Datepicker` to the `components` property of whichever component you wish to use the datepicker on, then use `<datepicker placeholder="Select Date"/>`.

**Comment by rashed-jitu** [comment]
@liam-potter I know <my-component> is just example, but when I am declaring a global component, it should be available to any component, Any way I have solved this by this way, 
`import Datepicker from 'vuejs-datepicker'` 
`Vue.component('my-component', Datepicker)`
But in the example they are saying to use 
`Vue.component('my-component', {
components: {
Datepicker
}
})`
But the example was not working.

**Comment by liam-potter** [comment]
The example is showing you how to inject the component into an existing component, not how to create a new component for the Datepicker itself.

The following line in the example takes care of setting it up as a component for you:
```
import Datepicker from 'vuejs-datepicker';
```

**Comment by rashed-jitu** [comment]
I got it now, Thank you for your reply. I was confused about it, How should I use it.

**Comment by Mian-Muhammad-Sumair** [comment]
> I got it now, Thank you for your reply. I was confused about it, How should I use it.



> I got it now, Thank you for your reply. I was confused about it, How should I use it.

Brother you done very well ,By help of You i  solved my problem

**Comment by tomaszs** [comment]
I have stumbled upon the same issue. After adding undocumented piece of code mentioned above (thanks!):

```
import Datepicker from "vuejs-datepicker";
Vue.component("vuejs-datepicker", Datepicker);
```

I get an error:

Could not find a declaration file for module 'vuejs-datepicker'. '...node_modules/.pnpm/vuejs-datepicker@1.6.2_vue@2.7.14/node_modules/vuejs-datepicker/dist/vuejs-datepicker.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/vuejs-datepicker` if it exists or add a new declaration (.d.ts) file containing `declare module 'vuejs-datepicker';`

When calling:

`pnpm i --save-dev @types/vuejs-datepicker`

I get an error stating there is no type package like this.

And most importantly, the date picker looks like this:

![image](https://user-images.githubusercontent.com/834977/220895790-e3e5a047-4a5c-42dd-bbf8-0920e774c23a.png)

I was debugging it for 2 hours. Just to learn that in spite of lack of types, when I click in the hollow space I see this:

![image](https://user-images.githubusercontent.com/834977/220895943-db826ad7-9546-499a-a79c-b130d0962a00.png)

I don't know if it's only me, but the documentation and initial visualization of the calendar (if it's not caused by my styles), could greatly benefit adoption of this great component.
