### ISSUE TITLE
Setting typeable causes date value to go blank

### ISSUE THREAD

**Issue by jeffmath** [charliekassel/vuejs-datepicker#489]
In version 1.2.0.

Steps:

1. Set the `typeable` property on picker
1. Type a date into the picker, hit enter
1. Use the calendar to enter a date into the picker
1. Remove focus from the picker
1. Notice that the picker input is now empty

**Comment by dweldon** [comment]
I notice a similar issue in `1.3.0`. After typing a date, all subsequent date selections via the picker will not alter the displayed value.

**Comment by andrew-boyd** [comment]
Same issue here as @dweldon. If you modify the date by typing, then any new selection via the picker just re-displays whatever the value of the typed date was. The actual data changes, but the display remains stuck on the typed date value.

**Comment by Julioocz** [comment]
@andrew-boyd I managed to fix that problem by setting the input data property `typedDate` to `false` when the picker closes (or a date is selected manually).
```
handleClose() {
        const input = this.$refs.datepicker.$children[0];
        input.typedDate = false;
}
```
Its a bit hacky but works. I'm having another problem though. If the input has an initial value and the picker is opened and nothing is choosed the input goes blank.

**Comment by Julioocz** [comment]
The problem here seems to be in this part of `DateInput.vue`
```
    /**
     * nullify the typed date to defer to regular formatting
     * called once the input is blurred
     */
    inputBlurred () {
      if (this.typeable && isNaN(Date.parse(this.input.value))) {
        this.clearDate()
        this.input.value = null
        this.typedDate = null
      }
      this.$emit('closeCalendar')
    },
```
I patched it to just emit the event. The defering wasn't working before and it's working fine now.

**Comment by SerikK** [comment]
If you select 13 or higher, it is the same blank

**Comment by RipkensLar** [comment]
@SerikK same for me.

**Comment by maritaria** [comment]
Please make a minor package release so we can use this fix through npm

**Comment by kennardconsulting** [comment]
+1

**Comment by milp** [comment]
Please fix this issue! It is still clearing out the input field. Also, the reason why I am using typeable = true in the first place is because I dont want the field to be displayed as greyed out.

**Comment by SerikK** [comment]
@charliekassel Please reopen issue

**Comment by charliekassel** [comment]
Sorry, I can't recreate the issue.
https://jsfiddle.net/h9wf3kng/

**Comment by milp** [comment]
First of all, Thank you very much for creating that Fiddle.
I saw what is happening here. It is "working" for you because you are manually typing the date in this very specific format (yyyy-m-d)
If ANY other format is used i.e. m-d-yyy or d-m-yyy, the logic deems that the value is incorrect (NaN ?) and thus clears out the display.
----------------------

Having cleared that issue, I have no idea why your date field is NOT showing greyed background (as behind the scenes the field becomes readonly=true).
I see a proper greyed-out field and that can give the impression to the user that the field is disabled. (I am not displaying any calendar popup button).

**Comment by milp** [comment]
What I'm trying to say is:
I would rather NOT have the field to be typeable but at the same time NOT have the field's background to be greyed out.

**Comment by milp** [comment]
This is what I did to alleviate my issue:

`
input[readonly] {
  background-color: white !important;
}
`

**Comment by ideafm** [comment]
Here is issue https://jsfiddle.net/h9wf3kng/2/

**Comment by Waynestay** [comment]
Hi, noting the same issue still exists when the day is 13 or higher, date format is DD/MM/YYYY and typeable is true. Is there a solution? I do actually want the field to be typeable.

**Comment by SerikK** [comment]
@charliekassel can you watch the problem above?

**Comment by valsaven** [comment]
I've got such problem with `vuejs-datepicker": "^1.5.4"`.
Any solution?

**Comment by bitkorn** [comment]
yes @Waynestay , 13 or higher. My date format is dd.MM.yyyy

**Comment by henhen87** [comment]
I have my calendar as typeable and use a format function to customize the date. The function mentioned by @Julioocz will clear the input when user blurs/goes out of focus on the input box. 

This is happening on Firefox for Mac, but windows it seems to not be a problem for some reason.

The custom date format function I have just sets the date as `dd-MMM-yyyy` (01-Jan-2019).

The function will clear the input because that string date is treated as `isNaN` and will clear the input.

**Comment by quanhub** [comment]
I'm having the same problem in Chrome

**Comment by mikkokut** [comment]
Same here

**Comment by ABackw** [comment]
I can confirm too. The bug has returned.
