### ISSUE TITLE
How to open the datepicker on focus and hide on blur

### ISSUE THREAD

**Issue by MuhammadRahman-awin** [charliekassel/vuejs-datepicker#560]
Hi,

I am trying to open the datapicker when it gets tab focus on it so my user will be aware to click on the date.

Is there any how I can do that?

**Comment by MuhammadRahman-awin** [comment]
I have managed it to work, somewhat.
Basically the datepicker field does not recognise the focus event at all, therefore, on my form, I added a blur event on the field before the datepicker. 

`   <div> previous field
        <input type="text" @blur="showDatepicker" />
    </div>
    <div>
      date
      <datepicker
        ref="datepicker"
        :typeable="true"
      />
    </div>
    <div> next field
      <input type="text">
    </div>`

And then in my JS 
`    showDatepicker() {
        this.$refs.datepicker.$children[0].$emit('showCalendar')
    },`

But realistically I want the focus to show the calendar. The current solution works but if user does a focus back from the 'next field' the calendar will not show up.

Thanks.

**Comment by charliekassel** [comment]
I've played with this in the past but not made a satisfactory attempt at solving it.
For now I'm not supporting it.

**Comment by abastardi** [comment]
Would you take a pull request for something like a `showOnFocus` prop?

**Comment by wpatter6** [comment]
`@focusin.native="open" @focusout.native="close"` works

**Comment by abastardi** [comment]
> `@focusin.native="open" @focusout.native="close"` works

What does your `open` method do? There does not appear to be an API to open the calendar. There is a `showCalendar` method that can be called on the parent of the `input` element ref, but it's tricky to access that component, and that does not appear to be part of the API. Furthermore, you cannot simply call `showCalendar` on every `focusin` event. If called when there is a click to focus the field, the `focusin` handler will open the calendar, and then the built-in click handler will immediately close it. So, you have to distinguish between a `focusin` event caused by clicking and one caused by tabbing into the field (this can be done by checking for a `mousedown` event right before the `focusin` event, which implies a click rather than a tab).

**Comment by wpatter6** [comment]
Here's my current function: 

`           open() {
                if(!this.$refs.picker.isOpen) {
                    this.$refs.picker.$el.querySelector("input").focus();
                    this.$refs.picker.showCalendar();
                }
            },
            close() {
                if(this.$refs.picker.isOpen) {
                    this.$refs.picker.close(true);
                }
            }`

Some of the methods aren't documented, but I found them by reading the component code

**Comment by abastardi** [comment]
Yes, I'm doing something similar. The problem is that `showCalendar()` is a toggle and will instead close the calendar if it is already open. So, if you set up a `focusin` handler as you have, it does not work if the user clicks on the input because the `focusin` handler first opens the calendar via the `showCalendar` method, and then the built-in `click` handler ends up immediately closing the calendar when it calls `showCalendar` a second time. I resolved this by setting up both `focusin` and `mousedown`/`mouseup` event handlers and using the `mousedown`/`mouseup` state to determine if a given `focusin` event is the result of a tab or a click.

`vuejs-datepicker` could more elegantly handle this shortcoming by adding something like a `showOnFocus` prop. When `true`, instead of using an `@click` handler to trigger the calendar, it could use an `@focus` handler (which would trigger on both tabs and clicks).
