### ISSUE TITLE
Allow escape key to clear input?

### ISSUE THREAD

**Issue by InstanceOfMichael** [charliekassel/vuejs-datepicker#567]
I would like to optionally enable the escape key (or another key) to clear the input if and only if the calendar is already closed. This will allow a user to clear the input without using the mouse.

https://github.com/charliekassel/vuejs-datepicker/blob/master/src/components/DateInput.vue#L111

**Comment by charliekassel** [comment]
I don't think that is good UI and not consistent with other inputs.

**Comment by InstanceOfMichael** [comment]
What do other inputs do?

**Comment by nelson6e65** [comment]
@InstanceOfMichael It's inconsistent because `Esc` is not semantic for "Clear input". Maybe the `Delete` key or `D` could be better.

**BUT...**

If you want to clear the input with a key press (ex. `Delete`), add a listener for @kepdown (adjust) to its parent container and call to the `clearDate()`, via `$refs` (see https://github.com/charliekassel/vuejs-datepicker/issues/424), when user uses the `Delete` key (or the key you want). So, when date picker is not focused, you can clear the data programmatically.
